[theme]
base = "light"
primaryColor = "#1ABC9C"
backgroundColor = "#ECF0F1"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2C3E50"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
